/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    posts: Post;
    matches: Match;
    events: Event;
    venues: Venue;
    members: Member;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    venues: VenuesSelect<false> | VenuesSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('sv' | 'en') | ('sv' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'sv' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Redaktörer och administratörer som kan logga in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Redaktörer kan skriva, publicera och ladda upp bilder. Administratörer kan dessutom bjuda in fler och se medlemsregistret.
   */
  role: 'admin' | 'editor';
  showInTeam?: boolean | null;
  /**
   * T.ex. "Ordförande", "Skribent" eller "Poddredaktör".
   */
  title?: string | null;
  /**
   * Visas på sidan Redaktionen och under dina artiklar.
   */
  bio?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Årtal, t.ex. 1997.
   */
  supporterSince?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Alla bilder som används på sajten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beskriv kort vad bilden föreställer. Läses upp för synskadade besökare och visas om bilden inte laddar. T.ex. "Cole Palmer jublar efter mål".
   */
  alt: string;
  /**
   * Valfritt. Visas under bilden i artikeln.
   */
  caption?: string | null;
  /**
   * Valfritt, men ange alltid källa för bilder du inte tagit själv.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Ämnen att sortera artiklar under.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Fylls i automatiskt från rubriken. Ändra bara om du vet vad du gör — en publicerad artikel som byter slug tappar sina gamla länkar.
   */
  slug?: string | null;
  /**
   * Valfritt. Visas överst på kategorisidan.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nyheter, matchreferat, spelarbetyg och krönikor.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Visas överst i artikeln och i alla listor. Dra och släpp en bild här — du kan ladda upp direkt.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Kort sammanfattning som visas i listor. Lämnar du fältet tomt skapas en ingress automatiskt från artikelns första stycke.
   */
  excerpt?: string | null;
  /**
   * Styr hur artikeln märks upp i listorna. Samma indelning som vi använt på SvenskaFans.
   */
  articleType?: ('nyhet' | 'infor' | 'referat' | 'spelarbetyg' | 'kronika' | 'foreningen' | 'intervju') | null;
  /**
   * Valfritt. Används för filtrering på nyhetssidan.
   */
  category?: (number | null) | Category;
  /**
   * Koppla ett referat, spelarbetyg eller inför-text till rätt match, så dyker artikeln upp i matchcentret.
   */
  relatedMatch?: (number | null) | Match;
  /**
   * Valfritt. T.ex. spelarnamn eller motståndare.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Valfritt. Lämnar du fälten tomma används rubriken och ingressen automatiskt.
   */
  seo?: {
    /**
     * Max ca 60 tecken. Tomt = artikelns rubrik används.
     */
    metaTitle?: string | null;
    /**
     * Max ca 160 tecken. Tomt = ingressen används.
     */
    metaDescription?: string | null;
    /**
     * Tomt = huvudbilden används när någon delar artikeln.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Fylls i automatiskt från rubriken. Ändra bara om du vet vad du gör — en publicerad artikel som byter slug tappar sina gamla länkar.
   */
  slug?: string | null;
  /**
   * Sätts till dig automatiskt. Ändra om någon annan skrivit texten.
   */
  author?: (number | null) | User;
  /**
   * För texter som flyttats hit utifrån. Visas som skribent när personen inte har ett konto här. Lämna tom för egna texter.
   */
  byline?: string | null;
  /**
   * Var texten publicerades först. Visas som en källhänvisning under artikeln.
   */
  sourceUrl?: string | null;
  /**
   * Fylls i automatiskt när du publicerar.
   */
  publishedAt?: string | null;
  /**
   * Lyfter artikeln till den stora puffen högst upp.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Föreningens egna matchsidor. Spelschema och tabell hämtas automatiskt — här lägger ni till referat, betyg och var vi ses.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  opponent: string;
  date: string;
  team: 'herrar' | 'damer' | 'akademin';
  homeOrAway: 'home' | 'away' | 'neutral';
  competition:
    | 'premier-league'
    | 'champions-league'
    | 'europa-league'
    | 'fa-cup'
    | 'efl-cup'
    | 'wsl'
    | 'friendly'
    | 'other';
  venue?: string | null;
  status: 'upcoming' | 'live' | 'finished';
  /**
   * Fylls i när matchen är slut. Alltid Chelseas mål först.
   */
  result?: {
    chelseaGoals?: number | null;
    opponentGoals?: number | null;
  };
  /**
   * Vilka mötesplatser som visar den här matchen.
   */
  watchAt?: (number | Venue)[] | null;
  tvChannel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Puben eller platsen där vi ses och ser matcherna, stad för stad.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: number;
  city: string;
  name: string;
  /**
   * Fylls i automatiskt från rubriken. Ändra bara om du vet vad du gör — en publicerad artikel som byter slug tappar sina gamla länkar.
   */
  slug?: string | null;
  address?: string | null;
  /**
   * Berätta kort hur det funkar — var ni brukar sitta, om det behövs bokning, vem man frågar efter.
   */
  description?: string | null;
  contactName?: string | null;
  contactEmail?: string | null;
  /**
   * Valfritt. Klistra in en Google Maps-länk.
   */
  mapsUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Avmarkera om stället inte längre gäller, istället för att radera.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pubkvällar, resor, årsmöten och andra träffar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Fylls i automatiskt från rubriken. Ändra bara om du vet vad du gör — en publicerad artikel som byter slug tappar sina gamla länkar.
   */
  slug?: string | null;
  date: string;
  /**
   * Valfritt.
   */
  endDate?: string | null;
  eventType: 'pubkvall' | 'resa' | 'arsmote' | 'traff' | 'annat';
  city?: string | null;
  /**
   * Namn och gärna adress, t.ex. "The Bishops Arms, Vasagatan 1".
   */
  location: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  /**
   * Valfritt.
   */
  maxAttendees?: number | null;
  /**
   * Valfritt. Full adress inklusive https://
   */
  registrationLink?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * GDPR: minimalt medlemsregister. Inga personnummer eller känsliga uppgifter — lägg aldrig till sådana fält.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  /**
   * Nya ansökningar från webbformuläret hamnar som "Ny ansökan".
   */
  status: 'pending' | 'active' | 'expired' | 'cancelled';
  name: string;
  email: string;
  /**
   * Valfritt.
   */
  phone?: string | null;
  /**
   * Hjälper oss ordna träffar på rätt ställen.
   */
  city?: string | null;
  membershipType: 'standard' | 'familj' | 'ungdom' | 'heders';
  /**
   * Fritext som personen skrev i ansökningsformuläret.
   */
  message?: string | null;
  joinedAt: string;
  /**
   * Fylls i när medlemsavgiften betalats.
   */
  expiresAt?: string | null;
  newsletter?: boolean | null;
  /**
   * Syns bara här i admin. Skriv aldrig känsliga uppgifter.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fasta sidor som Om oss, Biljetter, Arenaguide och Reseguide.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Valfri kort text som visas under rubriken.
   */
  intro?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Bygg sidan genom att lägga till block. Du kan dra dem för att ändra ordning.
   */
  content?:
    | (
        | {
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            heading: string;
            items?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'factsBlock';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel: string;
            /**
             * Intern länk som /sv/medlemskap, eller full https://-adress.
             */
            buttonUrl: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
      )[]
    | null;
  /**
   * Valfritt. Lämnar du fälten tomma används rubriken och ingressen automatiskt.
   */
  seo?: {
    /**
     * Max ca 60 tecken. Tomt = artikelns rubrik används.
     */
    metaTitle?: string | null;
    /**
     * Max ca 160 tecken. Tomt = ingressen används.
     */
    metaDescription?: string | null;
    /**
     * Tomt = huvudbilden används när någon delar artikeln.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Fylls i automatiskt från rubriken. Ändra bara om du vet vad du gör — en publicerad artikel som byter slug tappar sina gamla länkar.
   */
  slug?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'venues';
        value: number | Venue;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  showInTeam?: T;
  title?: T;
  bio?: T;
  avatar?: T;
  supporterSince?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  featuredImage?: T;
  excerpt?: T;
  articleType?: T;
  category?: T;
  relatedMatch?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  slug?: T;
  author?: T;
  byline?: T;
  sourceUrl?: T;
  publishedAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  opponent?: T;
  date?: T;
  team?: T;
  homeOrAway?: T;
  competition?: T;
  venue?: T;
  status?: T;
  result?:
    | T
    | {
        chelseaGoals?: T;
        opponentGoals?: T;
      };
  watchAt?: T;
  tvChannel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  endDate?: T;
  eventType?: T;
  city?: T;
  location?: T;
  description?: T;
  featuredImage?: T;
  maxAttendees?: T;
  registrationLink?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  city?: T;
  name?: T;
  slug?: T;
  address?: T;
  description?: T;
  contactName?: T;
  contactEmail?: T;
  mapsUrl?: T;
  image?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  city?: T;
  membershipType?: T;
  message?: T;
  joinedAt?: T;
  expiresAt?: T;
  newsletter?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  heroImage?: T;
  content?:
    | T
    | {
        richTextBlock?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        factsBlock?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  slug?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Namn, kontaktuppgifter, sociala medier och vilka moduler som visas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Används av Google och när sajten delas i sociala medier.
   */
  description?: string | null;
  logo?: (number | null) | Media;
  email?: string | null;
  orgNumber?: string | null;
  /**
   * T.ex. "250 kr per år". Visas på medlemssidan.
   */
  membershipFee?: string | null;
  /**
   * Visas i instruktionerna för att betala medlemsavgiften.
   */
  swish?: string | null;
  bankgiro?: string | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'x' | 'youtube' | 'tiktok' | 'discord' | 'spotify' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  showChelseaNews?: boolean | null;
  showPodcast?: boolean | null;
  /**
   * Under övergången kan vi visa arkivet från SvenskaFans. Slå av den här när allt innehåll flyttat hit.
   */
  showSvenskaFans?: boolean | null;
  /**
   * En rad högst upp på sajten, t.ex. inför en resa eller ett årsmöte.
   */
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    linkLabel?: string | null;
    /**
     * Intern länk som /sv/evenemang eller full https://-adress.
     */
    linkUrl?: string | null;
  };
  forumUrl?: string | null;
  podcastUrl?: string | null;
  /**
   * Valfritt. Länk till Fantasy Premier League-ligan.
   */
  fplLeagueUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Huvudmenyn högst upp på sajten. Dra raderna för att ändra ordning.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Lämnas listan tom används sajtens standardmeny. Ett menyval kan ha undermeny.
   */
  items?:
    | {
        label: string;
        /**
         * Intern sida skrivs som /matcher. Extern länk med full https://-adress.
         */
        link: string;
        external?: boolean | null;
        children?:
          | {
              label: string;
              /**
               * Intern sida skrivs som /matcher. Extern länk med full https://-adress.
               */
              link: string;
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Intern sida skrivs som /matcher. Extern länk med full https://-adress.
               */
              link: string;
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  email?: T;
  orgNumber?: T;
  membershipFee?: T;
  swish?: T;
  bankgiro?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  showChelseaNews?: T;
  showPodcast?: T;
  showSvenskaFans?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  forumUrl?: T;
  podcastUrl?: T;
  fplLeagueUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        link?: T;
        external?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}